.TH FREQ 1 "2024" "1.0" "User Commands"
.SH NAME
freq \- count and display the frequency of distinct elements
.SH SYNOPSIS
.B freq
[ \-haDRsidflS ] [ \fB\-D\fR \fIDELIM\fR] [ \fB\-S\fR \fIsize\fR ] [ \fB\-i\fR | \fB\-d\fR | \fB\-f\fR | \fB\-l\fR ] [ \fB\-\-delimiter\fR=\fIDELIM\fR ] [ \fB\-\-struct\fR=\fIsize\fR ] [ file ... ]
.SH DESCRIPTION
.B freq
reads from stdin or input files. Counts the frequency of distinct elements. It outputs the elements along with their counts in the following format:
.sp
element:count
.sp
By default, \fBfreq\fR processes input as delimited text. It can also process byte streams and handle various data types using appropriate options.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display help information and exit.
.TP
.BR \-a ", " \-\-aggregate
Aggregate the input files and perform freq on the aggregated input set
.TP
.BR \-D " " \fIDELIM\fR ", " \fB\-\-delimiter\fR=\fIDELIM\fB
Specify the delimiter to split input elements (supports regex). If not specified, the default delimiter is empty string.
.TP
.BR \-R ", " \-\-raw
Process the input as a raw byte stream, without delimiters. Assumes packed data. 
.TP
.BR \-s ", " \-\-sort
Sort the output by the element values.
.TP
.BR \-i ", " \-\-int
Interpret the input as integers.
.TP
.BR \-d ", " \-\-double
Interpret the input as doubles.
.TP
.BR \-f ", " \-\-float
Interpret the input as floats.
.TP
.BR \-l ", " \-\-long
Interpret the input as long integers.
.TP
.BR \-S " " \fIsize\fR ", " \-\-struct= \fIsize\fR
Interpret the input as packed structs of \fIsize\fR bytes. Requires the \fB\-R\fR (or \fB\-\-raw\fR) option to be selected.
.SH EXAMPLES
.TP
Count distinct chars in a file using no delimiters (each char read is counted until EOF):
.sp
.B freq
file.txt
.TP
Use a comma as the delimiter for splitting input elements:
.sp
.B freq \-D ","
file.csv
.TP
Count distinct integers from a byte stream:
.sp
.B freq \-\-raw \-i
file.bin
.TP
Sort the output while counting distinct floats:
.sp
.B freq \-f \-s
file.txt
.SH SEE ALSO
.B sort(1),
.B uniq(1)
.SH HISTORY
.TP
The first version of \fBfreq\fR appeared as the \fIauthor\fR's solution to the question 6-4 in the book \fBPractice of Programming\fR by Brian W. Kernighan and Rob Pike.
.SH AUTHOR
Written by John Demir
.SH REPORTING BUGS
Report bugs to had287@nyu.edu

